### ISSUE TITLE
画像分割する

### ISSUE THREAD

**Issue by shunsuke-tamura** [scla-sagauniv/RustKimushun#2]
## 背景
同じ解像度の画像をOCRかけたら制度出ないのに、一部分だけ切り取ってかけたら正確に読み取れた

## やること
入力された画像(縦長)を縦にn等分する関数作る

**Comment by nnnnn81** [comment]
# できた
https://github.com/scla-sagauniv/RustKimushun_demo/tree/main/issue2-split-image
