### ISSUE TITLE
画像から表示する文字列に変換するロジックを組む

### ISSUE THREAD

**Issue by shunsuke-tamura** [scla-sagauniv/RustKimushun#5]
## やること
将来的に画面に表示して受け取る側のカメラで読み取ることになる文字列データを画像から生成するロジックを組む
頭の中では
1. 画像をバイナリで読み込む
2. 一旦RGG32段階、文字種(A~Z、a~z、0~9、+-、)だと仮定すると log2(32 ^ 3 * (26 * 2 + 12)) = 21
4. そうすると、1文字で21bit表せる
5. ですので、全体のbitを21分割する
6. それの前から5bitがR、5bitがG、5bitがB、6bitが文字種で構成できる
7. に変換する関数を作る

**Comment by ryutaro-kimura** [comment]
https://github.com/scla-sagauniv/RustKimushun_demo/tree/main/issue5-img-to-str
